### ISSUE TITLE
[PE-D][Tester B] `addrecipe` empty steps takes steps from previous `addrecipe` command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-3/tp#142] opened 2023-11-03 20:20 UTC
![image.png](https://raw.githubusercontent.com/kenvynKwek/ped/main/files/4c498019-72c0-4160-9909-026a5ebe8d7a.png)

Problem: adding a recipe without keying in the steps takes steps from previous `addrecipe` command

Steps to reproduce:
1. prerequisite - enter a valid `addrecipe` command
2. add a new recipe `addrecipe`
3. enter a sample name `pancake`
4. enter ingredients `vanilla extract 100g`
5. enter `steps start`
6. enter `complete recipe` without entering any steps

Potential improvement: Enable `addrecipe` command to accept empty steps, or output an appropriate error message when no steps are detected.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kenvynKwek/ped#6

**Comment by TohLiYuan** [comment] 2023-11-04 00:26
Duplicate of #133

**Closed by TohLiYuan** 2023-11-04 00:26 UTC
