### ISSUE TITLE
[PE-D][Tester C] add allows quantity to be 0

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F10-3/tp#153] opened 2023-11-03 21:12 UTC
![image.png](https://raw.githubusercontent.com/owenyeo/ped/main/files/2f6c3c0b-efb1-4c46-8b42-b04e233e3fbb.png)

I can add ingredients with quantity of zero. Here, I put add n/whoa q/0 u/kg 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: owenyeo/ped#11

**Comment by TohLiYuan** [comment] 2023-11-04 00:02
Somewhat duplicate of #127 , invalid values will be handled in the next bug fix

**Closed by TohLiYuan** 2023-11-04 00:02 UTC
Labels: duplicate
