### ISSUE TITLE
[PE-D][Tester C] UG not updated to reflect Modify was added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-3/tp#148] opened 2023-11-03 20:53 UTC
Modify is working properly, but is not updated in the UG.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: owenyeo/ped#9

**Comment by TohLiYuan** [comment] 2023-11-04 00:29
Duplicate of #141

**Closed by TohLiYuan** 2023-11-04 00:29 UTC
