### ISSUE TITLE
[PE-D][Tester C] UG does not contain what units are accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F10-3/tp#126] opened 2023-11-03 18:21 UTC
UG does not tell the user what units is accepted by the command, thus I cannot properly use the functions as some units that I thought can be put in, such as Oz, ml, L, was not accepted as proper units. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: owenyeo/ped#2

**Comment by TohLiYuan** [comment] 2023-11-04 03:20
Duplicate of #123

**Closed by TohLiYuan** 2023-11-04 03:20 UTC
Labels: duplicate
